name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch: 

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW  }}

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Get AKS configs
      - name: Connect to Kubernetes
        run: az aks get-credentials --resource-group bookInventory --name bookInventory --overwrite-existing 
      #
      # Builds the Docker image.
      #
      - name: Build
        run: chmod +x ./scripts/build-image.sh

      #
      # Publishes the Docker image to the container registry.
      #
      - name: Publish
        run: chmod +x ./scripts/push-image.sh

      #
      # Expands the configuration template and deploys the microservice.
      #
      - name: Deploy
        run: chmod +x ./scripts/deploy.sh
